#!/bin/bash
clean
echo "Welecome to the ngmp!"
# Detect nginx is installed or not
if [ -f nginx ]; then
    echo "WARNING: Nginx is installed, if continued, it will be overrided."
else
# Detect php is installed or not
if [ -f php-fpm ]; then
    echo "WARNING: PHP is installed, if continued, it will be overrided."
else
if [ -f mysql ]; then
    echo "WARNING: MySQL is installed, if continued, it will be overrided."
else
if [ -f mariadb ]; then
    echo "WARNING: MariaDB is installed, if continued, it will be overrided."
else
nginx:
echo "Select Nginx version:"
echo "1. Latest (1.25.4)"
echo "2. Stable (1.24.0)"
echo "3. Legacy (1.22.0)"
read -p "Please input your choice (1-3):" nginx_version
if [ "$nginx_version" == "1" ]; then
    nginx_version="1.25.4"
else
if [ "$nginx_version" == "2" ]; then
    nginx_version="1.24.0"
else
if [ "$nginx_version" == "3" ]; then
    nginx_version="1.22.0"
else
    echo "Invalid choice!"
    goto nginx
fi
:php
echo "Select PHP version:"
echo "1. 8.3"
echo "2. 8.2"
echo "3. 8.1"
echo "4. 8.0"
echo "5. 7.4"
read -p "Please input your choice (1-5):" php_version
if [ "$php_version" == "1"]; then
    php_version="8.3"
else
if [ "$php_version" == "2" ]; then
    php_version="8.2"
else
if [ "$php_version" == "3" ]; then
    php_version="8.1"
else
if [ "$php_version" == "4" ]; then
    php_version="8.0"
else
if [ "$php_version" == "5" ]; then
    php_version="7.4"
else
    echo "Invalid choice!"
    goto php
fi
:maraidb
echo "Select MariaDB version:"
echo "1. Latest (11.5.10)"
echo "2. Stable (10.11.29)"
echo "3. Legacy (10.7.38)"
echo "4. Legacy (10.6.15)"
read -p "Please input your choice (1-4):" mariadb_version
if [ "$mariadb_version" == "1" ]; then
    mariadb_version="11.5.10"
else
if [ "$mariadb_version" == "2" ]; then
    mariadb_version="10.11.29"
else
if [ "$mariadb_version" == "3" ]; then
    mariadb_version="10.7.38"
else
if [ "$mariadb_version" == "4" ]; then
    mariadb_version="10.6.15"
else
    echo "Invalid choice!"
    goto mariadb
fi
echo "Nginx version: $nginx_version"
echo "PHP version: $php_version"
echo "MariaDB version: $mariadb_version"
read -p "Do you want to continue? (y/n):" choice
if [ "$choice" == "y" ]; then
    echo "Installation started..."
    # Install Nginx dependency
    if [ -f apt ]; then
        sudo apt update
        sudo apt install -y build-essential libpcre3 libpcre3-dev zlib1g-dev
    else
    if [ -f yum ]; then
        sudo yum update -y
        sudo yum install -y gcc pcre-devel zlib-devel
    else
        echo "Unsupported package manager!"
        exit 1
    fi
    # Download Nginx
    wget https://nginx.org/download/nginx-$nginx_version.tar.gz
    tar -xvf nginx-$nginx_version.tar.gz
    cd nginx-$nginx_version
    # Configure Nginx
    ./configure --prefix=/usr/local/nginx --with-http_lua_module --with-http_ssl_module --add-module=src/lua-nginx-module
    if [ $? -ne 0 ]; then
        echo "Failed to configure Nginx!"
        exit 1
    fi
    # Compile and install Nginx
    make -j8 && sudo make install
    if [ $? -ne 0 ]; then
        echo "Failed to install Nginx!"
        exit 1
    fi
    # Create Nginx user
    sudo useradd -s /sbin/nologin www-data
    

